### PR TITLE
Create public README.md for org's profile page

### PR DESCRIPTION
**Pull request by duetosymmetry**
This will display as a banner above our pins and repos.

### CODE REVIEW

**Review by geoffrey4444 — CHANGES_REQUESTED** [review]
This is fine, but pretty sure everything in catalog_tools is superseded by stuff in sxs...I would check with Mike Boyle if that's the case, and if so, remove the link to catalog_tools

**Comment by moble** [comment]
Yeah, I believe all the main tasks in `catalog_tools` can be achieved by `sxs`, so it probably doesn't need to be advertised prominently.

**Comment by duetosymmetry** [comment]
Still open, should we merge?

**Review by moble — APPROVED** [review]
LGTM

**Comment by moble** [comment]
I think @geoffrey4444's requested change was addressed by your last commit, so unless @kidder chimes in soon, I say go for it.

**Comment by kidder** [comment]
I have no objection to this PR.

I am confused, however, about why this repo is forked from a github repo and not on its own as described by https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by duetosymmetry** [comment]
@kidder just out of convenience — they already had the appropriate file names, we changed the contents.

EDIT: We should probably delete the SECURITY.md file

**Pull request merged**
